### ISSUE TITLE
Depenency: libsodium 1.0.15 moved to old/

### ISSUE THREAD

**Issue by wallnutkraken** [jl777/komodo#1142]
### Describe the issue
In `depends/packages/libsodium.mk`, there is a url for libsodium 1.0.15, the link was previously
`https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz`

However, now the URL has to be

`https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.15.tar.gz`

Notice the *old* directory it's been moved to

#### If so, please list the steps to reproduce below:
1. Build komodo as specified

### Expected behaviour
It gets dependencies correctly

### Actual behaviour + errors
Fails to build due to dependency failure

curl: (22) The requested URL returned error: 404

**Comment by jl777** [comment]
I believe this is fixed
