### ISSUE TITLE
build-mac.sh broken

### ISSUE THREAD

**Issue by leto** [jl777/komodo#1232]
```
make[2]: *** No rule to make target `libcc.so', needed by `komodod'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

It seems that the CC makefile knows about so/dll/dylib, but our top level src/Makefile.am does not

**Comment by jl777** [comment]
this should be fixed now

**Comment by leto** [comment]
yes, I fixed this and forgot to close this
