### ISSUE TITLE
Consider changing type:cryptocondition to cc

### ISSUE THREAD

**Issue by siddhartha-crypto** [jl777/komodo#1375]
This issue tracker is only for technical issues related to komodod

General Komodo questions and/or support requests and are best directed to [Discord](https://komodoplatform.com/discord)

### Describe the issue
Please provide a general summary of the issue you're experiencing

We are deprecating all references of CryptoConditions, and replacing them with Custom Consensus

Via the documentation, I notice that in the `decodeccopret` rpc there is a direct reference to cryptoconditions.

See the issue here:

https://github.com/KomodoPlatform/developer-docs/blob/dev-theme/docs/basic-docs/komodo-api/util.md#decodeccopret

### Expected behaviour
Tell us what should happen

If it's not too confusing and causes no breaking changes, perhaps we should change `cryptoconditions` in the `type` property to just `cc`.

**Comment by jl777** [comment]
i dont mind changing the documentation, but i actually tried changing the code, but it ends up breaking things as there are just too many occurances internally

**Comment by siddhartha-crypto** [comment]
Okay.
