### ISSUE TITLE
Incorrect error message when AC.conf can't be found

### ISSUE THREAD

**Issue by leto** [jl777/komodo#1430]
This command is actually looking for HUSH3.conf, not komodo.conf, so this error could be confusing to users:

```
$ hush-cli-testnet getinfo
Error reading configuration file: Missing komodo.conf
```

**Comment by jl777** [comment]
can you fix it?

**Comment by AstrohackerX** [comment]
util.h line 150-153 looking for a komodo.conf

**Comment by leto** [comment]
@jl777 I made this issue to make sure I didn't forget about it. Yes I can fix it, if somebody doesn't beat me to it. 

@AstrohackerX do you want to try to fix this and I code review?

**Comment by AstrohackerX** [comment]
@leto yep, I'll let you know

**Comment by AstrohackerX** [comment]
Done (tested)
https://github.com/AstrohackerX/komodo/commit/6f2ce815772114531685524d3545bbff2abeb079

**Comment by leto** [comment]
@AstrohackerX nice :+1:
