### ISSUE TITLE
Compile error on FSM branch with build-mac.sh

### ISSUE THREAD

**Issue by leto** [jl777/komodo#1508]
Some warnings become errors with build-mac and prevent the build:

https://gist.github.com/leto/d8c3bfc169520768424ae22e034eb10c

**Comment by tonymorony** [comment]
We've switched from gcc-6 to gcc-8 on OSX because of linkage errors on gcc-6.

Could you please `brew install gcc@8` and try to build-mac.sh again?

**Comment by leto** [comment]
@tonymorony just giving an update that we are waiting on @deckersu to figure out exactly what is wrong

**Comment by DeckerSU** [comment]
try this branch https://github.com/DeckerSU/komodo/tree/patch-fsm-gcc8 , if all is ok - i will made a PR into FSM.

**Comment by tonymorony** [comment]
FSM branch compiling now on my side after this https://github.com/jl777/komodo/pull/1511 PR merge

**Comment by ca333** [comment]
macOS build fixed with https://github.com/jl777/komodo/commit/34192e2b229868d356f98c78527346a0887f9775 and https://github.com/jl777/komodo/commit/34192e2b229868d356f98c78527346a0887f9775 - closing this
