### ISSUE TITLE
[nSPV] skipcount param does not work for listunspent and listtransasctions calls

### ISSUE THREAD

**Issue by SirSevenG** [jl777/komodo#1648]
same issue with libnspv: https://github.com/jl777/libnspv/issues/37
'skipcount' parameter has currently no effect.

To reporduce:

* take address with X amount of utxos/transactions
* call listtransactions with skipcount = 0
* call listtransactions with skipcount = N, N > 0

result: calls have same output
expected: 2nd call should have N less transactions/utxos in output

Commands might be used to check (for KMD):
```shell
./komodo-cli nspv_listunspent RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh

./komodo-cli nspv_listunspent RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh 0 30

./komodo-cli nspv_listtransactions RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh

./komodo-cli nspv_listtransactions RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh 0 30
```

**Comment by jl777** [comment]
please just use libnspv repo for all nspv issues
