### ISSUE TITLE
KV / kvsearch is not working properly with large strings

### ISSUE THREAD

**Issue by pbca26** [jl777/komodo#552]
kvsearch is breaking between value size 3879 and 4364

for your reference
size 3879 txid 9d8412344f7e2cc4ea393a25fcb8b51094e9cfcd1fb822f5485f9b256e17d840
size 4364 txid 53a28255533764631ec718a3a9d7f89da806ad95c124d91cd1ce97d26f472309

**Comment by jl777** [comment]
pushed fix to jl777 branch
