### ISSUE TITLE
KV / kvupdate doesn't return an updated value

### ISSUE THREAD

**Issue by pbca26** [jl777/komodo#553]
kvupdate always returns an initial value set for a key

pushed initial kv tx http://pizza.komodochainz.info/api/getrawtransaction?txid=cccbbeb911000e3966e221e039364117f5aa2754bc7c51db62acbe63ad942289&decrypt=1
pushed kv update after 30 mins http://pizza.komodochainz.info/api/getrawtransaction?txid=56848c4ca33e94f1dbe856401c1543adec3a6367824d202f496d214eb1b88882&decrypt=1

./komodo-cli -ac_name=PIZZA kvsearch kvtest
{
  "coin": "PIZZA",
  "currentheight": 18960,
  "key": "kvtest",
  "keylen": 6,
  "height": 18957,
  "expiration": 20397,
  "flags": 1,
  "value": "The most important part of a decentralized crypto coin/asset\\'s lifecycle, the ICO, is centralized. Being centralized, it is subject to the whims of government decrees about what can and cannot be ICO\\'ed. As long as you pay the required toll fees, you will be granted a license to sell coins/assets, unless it is deemed that it won’t be approved for whatever reason. As for how long this process takes, that is totally in the hands of whatever government agency is dealing with it.",
  "valuesize": 484
}

the above value belongs to txid cccbbeb911000e3966e221e039364117f5aa2754bc7c51db62acbe63ad942289
expected behaviour is to see an updated value from txid 56848c4ca33e94f1dbe856401c1543adec3a6367824d202f496d214eb1b88882

**Comment by jl777** [comment]
pushed fix to jl777 branch
