### ISSUE TITLE
fetch-params.sh problem 

### ISSUE THREAD

**Issue by igorvoltaic** [jl777/komodo#637]
SPROUT_PKEY_NAME='sprout-proving.key'
SPROUT_VKEY_NAME='sprout-verifying.key'
SPROUT_PKEY_URL="https://z.cash/downloads/$SPROUT_PKEY_NAME"
SPROUT_VKEY_URL="https://z.cash/downloads/$SPROUT_VKEY_NAME"

there are no .keys in [https://z.cash/downloads/](https://z.cash/downloads/) 
Checked with the browser.

I've changed `fetch-params.sh` as follows to get them, but i'm not sure if it is right thing to do.
SPROUT_PKEY_NAME='sprout-proving.key'
SPROUT_VKEY_NAME='sprout-verifying.key'
SPROUT_PKEY_URL="https://zensystem.io/downloads/$SPROUT_PKEY_NAME"
SPROUT_VKEY_URL="https://zensystem.io/downloads/$SPROUT_VKEY_NAME"

**Comment by igorvoltaic** [comment]
It does work, but it doesn't look good. That's why I just created an issue. Would be much better if the  keys are sourced from `komodoplatform.com` or komodo's GitHub. Looks like removed keys @ https://z.cash/downloads is not a temporary problem. They did it on purpose.

**Comment by jl777** [comment]
I just verified wget https://z.cash/downloads/sprout-proving.key is working, so not sure why it didnt work for you and if it works, there is no need to change it

**Comment by igorvoltaic** [comment]
guess this was a network problem  caused by telegram block :/ let's close this one.
