### ISSUE TITLE
Feature Request: totalsupply as part of getInfo return JSON

### ISSUE THREAD

**Issue by CHMEX** [jl777/komodo#719]
This is a feature request for `totalsupply` as part of getinfo JSON return on assetchains no idea if it's possible.
Currently getInfo returns a JSON with the `assetchainname`
```
{
  "version": 1001550,
  "protocolversion": 170003,
  "KMDversion": "0.1.1",
  "notarized": 18170,
  "prevMoMheight": 18170,
  "notarizedhash": "00003ed43e386be0a82bf38bf7b965d9a9e12233ab8e0e745c99737d01f88b92",
  "notarizedtxid": "58adec8562e6f3fb9839a1cf2b5e8850d1480fd6b2d17b711e8ec3a2d43cefe2",
  "notarizedtxid_height": "mempool",
  "KMDnotarized_height": 0,
  "notarized_confirms": 0,
  "walletversion": 60000,
  "balance": 0,
  "blocks": 18174,
  "longestchain": 18174,
  "timeoffset": 0,
  "tiptime": 1530688628,
  "connections": 8,
  "proxy": "",
  "difficulty": 45.26496236118357,
  "testnet": false,
  "keypoololdest": 1530647784,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": "",
  "name": "RFOX",
  "p2pport": 32268,
  "rpcport": 8265,
  "magic": 1141288268,
  "premine": 1000000000,
  "reward": 100000000
}
```

an additional field `"totalsupply"` should be possible to be calculated with `premine + (blocks * reward)` 
I understand this does not work for KMD because of the rewards and it would also need additional calculation for assetchains with variable rewards based on the blockheight which can be calculated from the other `ac_parameters`.

This feature would allow to patch the insight explorers to show the totalsupply which than can be used to mcap calculations.

**Comment by jl777** [comment]
I made a coinsupply rpc call instead. it is too expensive to do it by default and this way nodes that want this info can invoke it.
